# Generated by Django 4.1.3 on 2023-03-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_logging', '0007_migrate_old_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='change',
            name='ip_address',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AddField(
            model_name='change',
            name='user_agent',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='change',
            name='action',
            field=models.CharField(choices=[('Created', 'Added'), ('Updated', 'Changed'), ('Deleted', 'Deleted')], help_text='added|changed|deleted', max_length=7, verbose_name='Action'),
        ),
    ]
